/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package FloatedPage;

/**
 *
 * @author Esconde
 */
public class AddRoom extends javax.swing.JPanel {

    /**
     * Creates new form AddRoom
     */
    public AddRoom() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        textField2 = new Effect.TextField();
        textField3 = new Effect.TextField();
        textField4 = new Effect.TextField();
        textField5 = new Effect.TextField();
        textField6 = new Effect.TextField();
        textField7 = new Effect.TextField();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(326, 500));
        setRequestFocusEnabled(false);
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        jLabel1.setText("ADD ROOM");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 240, 60));

        textField2.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        textField2.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        textField2.setLabelText("Room Number");
        textField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textField2ActionPerformed(evt);
            }
        });
        add(textField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, 240, 40));

        textField3.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        textField3.setLabelText("Room Type");
        add(textField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 240, 40));

        textField4.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        textField4.setLabelText("Bed Type");
        add(textField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, 240, 40));

        textField5.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        textField5.setLabelText("Capacity");
        add(textField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, 240, 40));

        textField6.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        textField6.setLabelText("Capacity");
        add(textField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, 240, 40));

        textField7.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        textField7.setLabelText("Price Per Night");
        add(textField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 380, 240, 40));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("Add");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 460, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void textField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textField2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private Effect.TextField textField2;
    private Effect.TextField textField3;
    private Effect.TextField textField4;
    private Effect.TextField textField5;
    private Effect.TextField textField6;
    private Effect.TextField textField7;
    // End of variables declaration//GEN-END:variables
}
