/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package FloatedPage;

import Authentication.login;
import config.Session;
import config.dbConnector;
import config.passwordHasher;
import java.security.NoSuchAlgorithmException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;

/**
 *
 * @author Esconde
 */
public class change_pass extends javax.swing.JPanel {

    /**
     * Creates new form change_pass
     */
    public change_pass() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        oldpass = new javax.swing.JTextField();
        newpass = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        save_button = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setText("Change Password");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, -3, 140, 60));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 491, 60));

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel4.setText("Confirm Password");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, -1, -1));

        jLabel2.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel2.setText("Enter new Password");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 100, -1, -1));
        jPanel3.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 180, 290, 30));
        jPanel3.add(oldpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 60, 290, 30));
        jPanel3.add(newpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 120, 290, 30));

        jLabel3.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel3.setText("Current Password");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 40, -1, -1));

        jLabel5.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel5.setText("Cancel");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, -1, -1));

        save_button.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        save_button.setText("Save");
        save_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                save_buttonMouseClicked(evt);
            }
        });
        jPanel3.add(save_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 250, -1, -1));

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 490, 280));

        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 490, 340));
    }// </editor-fold>//GEN-END:initComponents

    private void save_buttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_save_buttonMouseClicked
        try {
            dbConnector con = new dbConnector();
            Session sess = new Session();
            Connection cn = con.getConnection();

            // Use PreparedStatement to prevent SQL injection
            String query = "SELECT password FROM user WHERE user_id = ?";
            PreparedStatement pst = cn.prepareStatement(query);

            // Ensure user_id is an integer if necessary
            pst.setInt(1, Integer.parseInt(sess.getUser_id())); // Fix potential type issue

            ResultSet rs = pst.executeQuery();

            if (rs.next()) {
                String oldbpass = rs.getString("password");

                // Verify old password instead of hashing it again
                if (passwordHasher.verifyPassword(oldpass.getText(), oldbpass)) { 
                    String npass = passwordHasher.hashPassword(newpass.getText());

                    // Secure password update with WHERE clause
                    String updateQuery = "UPDATE user SET password = ? WHERE user_id = ?";
                    PreparedStatement updatePst = cn.prepareStatement(updateQuery);
                    updatePst.setString(1, npass);
                    updatePst.setInt(2, Integer.parseInt(sess.getUser_id())); // Fix here

                    int rowsUpdated = updatePst.executeUpdate();
                    if (rowsUpdated > 0) {
                        JOptionPane.showMessageDialog(null, "Successfully Updated!");

                        // Open login form and close current dialog
                        login in = new login();
                        in.setVisible(true);
                        JDialog parentDialog = (JDialog) SwingUtilities.getWindowAncestor(this);
                        if (parentDialog != null) {
                            parentDialog.dispose();  // Closes the JDialog
                        }
                    } else {
                        JOptionPane.showMessageDialog(null, "Update Failed!", "Error", JOptionPane.ERROR_MESSAGE);
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "Old Password is Incorrect");
                }
            } else {
                JOptionPane.showMessageDialog(null, "User Not Found!", "Error", JOptionPane.ERROR_MESSAGE);
            }

            // Close resources
            rs.close();
            pst.close();
            cn.close();

        } catch (SQLException | NoSuchAlgorithmException | NumberFormatException ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(null, "Database Error! " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_save_buttonMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField newpass;
    private javax.swing.JTextField oldpass;
    private javax.swing.JLabel save_button;
    // End of variables declaration//GEN-END:variables
}
